version: '2'

services:
  
  ftpserver:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: ftpserver 
    container_name: ftpserver
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 10.0.40.100
 
  ftpclient:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: ftpclient
    container_name: ftpclient
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 10.0.40.101
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 10.0.40.0/24
          ip_range: 10.0.40.0/30
          gateway: 10.0.40.1
          aux_addresses:
            host1: 10.0.40.2
            host2: 10.0.40.3
#
#
#

